<h2>Library</h2>

In [5]:
import warnings
import pandas as pd
import statsmodels.api as sm

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

<h2>Main</h2>

<h3>Data Collection and Preparation:</h3>

In [6]:
# Load data
data = pd.read_csv('https://raw.githubusercontent.com/sibylhe/mmm_stan/main/data.csv')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 80 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   wk_strt_dt                209 non-null    object
 1   yr_nbr                    209 non-null    int64
 2   qtr_nbr                   209 non-null    int64
 3   prd                       209 non-null    int64
 4   wk_nbr                    209 non-null    int64
 5   wk_in_yr_nbr              209 non-null    int64
 6   mdip_dm                   209 non-null    int64
 7   mdip_inst                 209 non-null    int64
 8   mdip_nsp                  209 non-null    int64
 9   mdip_auddig               209 non-null    int64
 10  mdip_audtr                209 non-null    int64
 11  mdip_vidtr                209 non-null    int64
 12  mdip_viddig               209 non-null    int64
 13  mdip_so                   209 non-null    int64
 14  mdip_on                   209 non-null    int64
 15  mdip_em                   209 non-null    int64
 16  mdip_sms                  209 non-null    int64
 17  mdip_aff                  209 non-null    int64
 18  mdip_sem                  209 non-null    int64
 19  mdsp_dm                   209 non-null    float64
 20  mdsp_inst                 209 non-null    float64
 21  mdsp_nsp                  209 non-null    float64
 22  mdsp_auddig               209 non-null    float64
 23  mdsp_audtr                209 non-null    float64
 24  mdsp_vidtr                209 non-null    float64
 25  mdsp_viddig               209 non-null    float64
 26  mdsp_so                   209 non-null    float64
 27  mdsp_on                   209 non-null    float64
 28  mdsp_sem                  209 non-null    float64
 29  sales                     209 non-null    float64
 30  me_ics_all                209 non-null    float64
 31  me_gas_dpg                209 non-null    float64
 32  st_ct                     209 non-null    float64
 33  mrkdn_valadd_edw          209 non-null    float64
 34  mrkdn_pdm                 209 non-null    float64
 35  va_pub_0.15               209 non-null    int64
 36  va_pub_0.2                209 non-null    int64
 37  va_pub_0.25               209 non-null    int64
 38  va_pub_0.3                209 non-null    int64
 39  hldy_Black Friday         209 non-null    int64
 40  hldy_Christmas Day        209 non-null    int64
 41  hldy_Christmas Eve        209 non-null    int64
 42  hldy_Columbus Day         209 non-null    int64
 43  hldy_Cyber Monday         209 non-null    int64
 44  hldy_Day after Christmas  209 non-null    int64
 45  hldy_Easter               209 non-null    int64
 46  hldy_Father's Day         209 non-null    int64
 47  hldy_Green Monday         209 non-null    int64
 48  hldy_July 4th             209 non-null    int64
 49  hldy_Labor Day            209 non-null    int64
 50  hldy_MLK                  209 non-null    int64
 51  hldy_Memorial Day         209 non-null    int64
 52  hldy_Mother's Day         209 non-null    int64
 53  hldy_NYE                  209 non-null    int64
 54  hldy_New Year's Day       209 non-null    int64
 55  hldy_Pre Thanksgiving     209 non-null    int64
 56  hldy_Presidents Day       209 non-null    int64
 57  hldy_Prime Day            209 non-null    int64
 58  hldy_Thanksgiving         209 non-null    int64
 59  hldy_Valentine's Day      209 non-null    int64
 60  hldy_Veterans Day         209 non-null    int64
 61  seas_prd_1                209 non-null    int64
 62  seas_prd_2                209 non-null    int64
 63  seas_prd_3                209 non-null    int64
 64  seas_prd_4                209 non-null    int64
 65  seas_prd_5                209 non-null    int64
 66  seas_prd_6                209 non-null    int64
 67  seas_prd_7                209 non-null    int64
 68  seas_prd_8                209 non-null    int64
 69  seas_prd_9                209 non-null    int64
 70  seas_prd_12               209 non-null    int64
 71  seas_week_40              209 non-null    int64
 72  seas_week_41              209 non-null    int64
 73  seas_week_42              209 non-null    int64
 74  seas_week_43              209 non-null    int64
 75  seas_week_44              209 non-null    int64
 76  seas_week_45              209 non-null    int64
 77  seas_week_46              209 non-null    int64
 78  seas_week_47              209 non-null    int64
 79  seas_week_48              209 non-null    int64
dtypes: float64(16), int64(63), object(1)
memory usage: 130.8+ KB

In [7]:
data.rename(columns={'mdsp_dm': 'Direct Mail spend'
                     , 'mdsp_inst': 'Insert spend'
                     , 'mdsp_nsp': 'Newspaper spend'
                     , 'mdsp_audtr': 'Radio spend'
                     , 'mdsp_vidtr': 'TV spend'
                     , 'mdsp_so': 'Social Media spend'
                     , 'mdsp_on': 'Online Display spend'}, inplace=True)

data.head()

,wk_strt_dt,yr_nbr,qtr_nbr,prd,wk_nbr,wk_in_yr_nbr,mdip_dm,mdip_inst,mdip_nsp,mdip_auddig,mdip_audtr,mdip_vidtr,mdip_viddig,mdip_so,mdip_on,mdip_em,mdip_sms,mdip_aff,mdip_sem,Direct Mail spend,Insert spend,Newspaper spend,mdsp_auddig,Radio spend,TV spend,mdsp_viddig,Social Media spend,Online Display spend,mdsp_sem,sales,me_ics_all,me_gas_dpg,st_ct,mrkdn_valadd_edw,mrkdn_pdm,va_pub_0.15,va_pub_0.2,va_pub_0.25,va_pub_0.3,hldy_Black Friday,hldy_Christmas Day,hldy_Christmas Eve,hldy_Columbus Day,hldy_Cyber Monday,hldy_Day after Christmas,hldy_Easter,hldy_Father's Day,hldy_Green Monday,hldy_July 4th,hldy_Labor Day,hldy_MLK,hldy_Memorial Day,hldy_Mother's Day,hldy_NYE,hldy_New Year's Day,hldy_Pre Thanksgiving,hldy_Presidents Day,hldy_Prime Day,hldy_Thanksgiving,hldy_Valentine's Day,hldy_Veterans Day,seas_prd_1,seas_prd_2,seas_prd_3,seas_prd_4,seas_prd_5,seas_prd_6,seas_prd_7,seas_prd_8,seas_prd_9,seas_prd_12,seas_week_40,seas_week_41,seas_week_42,seas_week_43,seas_week_44,seas_week_45,seas_week_46,seas_week_47,seas_week_48
0,2014-08-03,2014,3,7,1,27,4863885,29087520,2421933,692315,37778097,10038746,2111112,0,3271007,1514755,27281,197828,83054,678410.26,129759.66,507635.16,2700.69,254134.14,216725.59,45397.90,0.0,61364.75,355954.51,72051457.64,82.5,3.595,716.285714,0.0,0.368029,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,2014-08-10,2014,3,7,2,28,20887502,8345120,3984494,475810,12063657,9847977,587184,0,4260715,2234569,27531,123688,83124,661097.71,70355.33,625719.37,5039.35,106602.98,108919.26,2903.36,0.0,132643.90,336306.72,78794770.54,82.5,3.582,716.428571,0.0,0.360911,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2,2014-08-17,2014,3,7,3,29,11097724,17276800,1846832,784732,5770115,7235336,1015658,0,4405992,1616990,55267,186781,79768,1874338.43,107720.37,277532.61,2610.93,59011.42,74032.19,8110.48,0.0,76741.27,344787.96,70071185.56,82.5,3.549,717.000000,0.0,0.344832,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,2014-08-24,2014,3,7,4,30,1023446,18468480,2394834,1032301,12174000,8625122,2149160,0,6638320,1897998,32470,122389,138936,306583.37,141708.61,186028.61,6032.91,178010.46,110995.66,6516.22,0.0,193043.55,365495.11,68642464.59,82.5,3.532,717.000000,0.0,0.356973,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,2014-08-31,2014,3,8,1,31,21109811,26659920,3312008,400456,31656134,19785657,2408661,0,4347752,2569158,55878,209969,87531,2366274.16,160691.30,706694.09,5187.32,144097.56,225140.84,19381.12,0.0,249612.89,401789.35,86190784.65,84.6,3.536,717.000000,0.0,0.359990,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

<h3>Model Selection:</h3>

In [8]:
# Model Selection:
import statsmodels.api as sm

# Create model
X = data[['TV spend', 'Online Display spend', 'Radio spend']]
y = data['sales']
X = sm.add_constant(X)  # Add a constant for the intercept

In [9]:
X.head()

   const   TV spend  Online Display spend  Radio spend
0    1.0  216725.59              61364.75    254134.14
1    1.0  108919.26             132643.90    106602.98
2    1.0   74032.19              76741.27     59011.42
3    1.0  110995.66             193043.55    178010.46
4    1.0  225140.84             249612.89    144097.56

<h3>Training the Model:</h3>

In [10]:
# The model has been trained when we used sm.OLS(y, X).fit()
model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.448
Method:                 Least Squares   F-statistic:                     57.27
Date:                Fri, 24 Oct 2025   Prob (F-statistic):           6.21e-27
Time:                        00:09:43   Log-Likelihood:                -3955.9
No. Observations:                 209   AIC:                             7920.
Df Residuals:                     205   BIC:                             7933.
Df Model:                           3
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                 6.679e+07   7.24e+06      9.225      0.000    5.25e+07    8.11e+07
TV spend               194.5686     22.564      8.623      0.000     150.082     239.055
Online Display spend    74.3041     27.124      2.739      0.007      20.826     127.782
Radio spend            -61.0892     49.578     -1.232      0.219    -158.837      36.659
==============================================================================
Omnibus:                       43.666   Durbin-Watson:                   2.154
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.168
Skew:                           0.986   Prob(JB):                     9.68e-21
Kurtosis:                       5.588   Cond. No.                     9.01e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.01e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

<h3>Model Evaluation:</h3>

In [11]:
# Evaluate the model (in this case, we'll use R-squared for simplicity)
r_squared = model.rsquared
print(f"R-squared: {r_squared}")

R-squared: 0.45596815437372085

<h3>Attribution Analysis:</h3>

In [12]:
# View the model coefficients to understand the impact of each channel on sales
coefficients = model.params
print("Model Coefficients:")
print(coefficients)

Model Coefficients:
const                   6.678621e+07
TV spend                1.945686e+02
Online Display spend    7.430407e+01
Radio spend            -6.108916e+01
dtype: float64

<h3>Budget Optimization:</h3>

In [13]:
# Calculate budget allocation (Example: Equal Allocation)
total_budget = 1000000  # Total advertising budget for a period
allocation_weights = [0.4, 0.3, 0.3]  # Allocation weights for TV, Online, and Radio
budget_allocation = [w * total_budget for w in allocation_weights]

budget_allocation

[400000.0, 300000.0, 300000.0]

<h3>Forecasting:</h3>

In [14]:
# Predict next month's sales based on anticipated advertising spend
new_advertising_spend = [60000, 35000, 17000]  # Anticipated spend for the next month
new_data = pd.DataFrame({'TV_spend': [new_advertising_spend[0]],
                         'Online_spend': [new_advertising_spend[1]],
                         'Radio_spend': [new_advertising_spend[2]],
                         'const': [1]})  # Include a constant for forecasting
predicted_sales = model.predict(new_data)

# Print results
print(f"Budget Allocation: {budget_allocation}")
print(f"Predicted Sales: {predicted_sales[0]}")

Budget Allocation: [400000.0, 300000.0, 300000.0]
Predicted Sales: 4007180768773.2383